# -*- coding: utf-8 -*-
STARS_PLANS = {
    "signals_week": {
        "title": "Signals 7 days",
        "title_ua": "Сигнали 7 днів",
        "title_ru": "Сигналы 7 дней",
        "title_en": "Signals 7 days",
        "description_ua": "Продовження доступу до сигналів і трекера на 7 днів.",
        "description_ru": "Продление доступа к сигналам и трекеру на 7 дней.",
        "description_en": "Extend access to signals and tracker for 7 days.",
        "payload": "extend_signals_7d",
        "plan_type": "signals",
        "duration_days": 7,
        "stars": 79,
        "amount_xtr": 79,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 79,
    },
    "tracker_1m_stars": {
        "title": "Bet Tracker 1 month",
        "title_ua": "Bet Tracker 1 місяць",
        "title_ru": "Bet Tracker 1 месяц",
        "title_en": "Bet Tracker 1 month",
        "description_ua": "Журнал ставок, статистика, емоційний трекер і ColdMind на 1 місяць.",
        "description_ru": "Журнал ставок, статистика, эмоциональный трекер и ColdMind на 1 месяц.",
        "description_en": "Bet journal, statistics, emotion tracker and ColdMind for 1 month.",
        "plan_type": "tracker",
        "duration_days": 30,
        "stars": 500,
        "amount_xtr": 500,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 500,
    },
    "tracker_6m_stars": {
        "title": "Bet Tracker 6 months",
        "title_ua": "Bet Tracker 6 місяців (-30%)",
        "title_ru": "Bet Tracker 6 месяцев (-30%)",
        "title_en": "Bet Tracker 6 months (-30%)",
        "description_ua": "Журнал ставок, статистика, емоційний трекер і ColdMind на 6 місяців.",
        "description_ru": "Журнал ставок, статистика, эмоциональный трекер и ColdMind на 6 месяцев.",
        "description_en": "Bet journal, statistics, emotion tracker and ColdMind for 6 months.",
        "plan_type": "tracker",
        "duration_days": 180,
        "stars": 2100,
        "amount_xtr": 2100,
        "is_promo": True,
        "first_payment_only": False,
        "full_price_xtr": 3000,
        "discount_percent": 30,
    },
    "stars_signals_vip": {
        "title_ua": "VIP Сигнали 30 днів",
        "title_ru": "VIP Сигналы 30 дней",
        "title_en": "VIP Signals 30 days",
        "plan_type": "signals_vip",
        "duration_days": 30,
        "amount_xtr": 1500,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 1500,
    },
    "stars_signals_elite": {
        "title_ua": "ELITE Сигнали 30 днів",
        "title_ru": "ELITE Сигналы 30 дней",
        "title_en": "ELITE Signals 30 days",
        "plan_type": "signals_elite",
        "duration_days": 30,
        "amount_xtr": 3750,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 3750,
    },
    "course_solo": {
        "title": "Курс ColdMind",
        "title_ua": "Курс ColdMind",
        "title_ru": "Курс ColdMind",
        "title_en": "Курс ColdMind",
        "description_ua": "Доступ до всіх модулів курсу ColdMind назавжди.",
        "description_ru": "Доступ ко всем модулям курса ColdMind навсегда.",
        "description_en": "Lifetime access to all ColdMind course modules.",
        "payload": "course_solo",
        "plan_type": "course_solo",
        "duration_days": 0,
        "amount_xtr": 1500,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 1500,
    },
    "course_tracker": {
        "title": "Курс ColdMind + Трекер (30 днів Basic)",
        "title_ua": "Курс ColdMind + Трекер (30 днів Basic)",
        "title_ru": "Курс ColdMind + Трекер (30 днів Basic)",
        "title_en": "Курс ColdMind + Трекер (30 днів Basic)",
        "description_ua": "Курс назавжди + 30 днів підписки Basic.",
        "description_ru": "Курс навсегда + 30 дней подписки Basic.",
        "description_en": "Lifetime course access + 30 days of Basic.",
        "payload": "course_tracker",
        "plan_type": "course_tracker",
        "duration_days": 30,
        "amount_xtr": 1575,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 1575,
    },
    "course_vip": {
        "title": "Курс ColdMind + VIP Сигнали (30 днів)",
        "title_ua": "Курс ColdMind + VIP Сигнали (30 днів)",
        "title_ru": "Курс ColdMind + VIP Сигнали (30 днів)",
        "title_en": "Курс ColdMind + VIP Сигнали (30 днів)",
        "description_ua": "Курс назавжди + 30 днів VIP.",
        "description_ru": "Курс навсегда + 30 дней VIP.",
        "description_en": "Lifetime course access + 30 days of VIP.",
        "payload": "course_vip",
        "plan_type": "course_vip",
        "duration_days": 30,
        "amount_xtr": 1875,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 1875,
    },
    "stars_basic_month": {
        "title_ua": "Basic 1 місяць",
        "title_ru": "Basic 1 месяц",
        "title_en": "Basic 1 month",
        "plan_type": "basic",
        "duration_days": 30,
        "amount_xtr": 525,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 525,
    },
    "stars_vip_week_199": {
        "title": "VIP  7 днів",
        "title_ua": "VIP  7 днів",
        "title_ru": "VIP  7 дней",
        "title_en": "VIP  7 days",
        "stars": 199,
        "plan_type": "vip",
        "duration_days": 7,
        "amount_xtr": 199,
        "is_promo": True,
        "first_payment_only": True,
        "offer_24h_only": True,
        "full_price_xtr": 1500,
    },
    "stars_vip_1m": {
        "title_ua": "VIP 1 місяць",
        "title_ru": "VIP 1 месяц",
        "title_en": "VIP 1 month",
        "plan_type": "vip",
        "duration_days": 30,
        "amount_xtr": 1500,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 1500,
    },
    "stars_vip_month": {
        "title": "VIP  30 днів",
        "title_ua": "VIP  30 днів",
        "title_ru": "VIP  30 дней",
        "title_en": "VIP  30 days",
        "plan_type": "vip",
        "duration_days": 30,
        "stars": 1500,
        "amount_xtr": 1500,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 1500,
    },
    "stars_vip_winback_1299": {
        "title": "VIP  30 днів",
        "title_ua": "VIP  30 днів",
        "title_ru": "VIP  30 дней",
        "title_en": "VIP  30 days",
        "plan_type": "vip",
        "duration_days": 30,
        "stars": 1299,
        "amount_xtr": 1299,
        "is_promo": True,
        "first_payment_only": False,
        "full_price_xtr": 1500,
        "discount_percent": 13,
    },
    "stars_basic_6m_promo": {
        "title_ua": "Basic 6 місяців (-29%)",
        "title_ru": "Basic 6 месяцев (-29%)",
        "title_en": "Basic 6 months (-29%)",
        "plan_type": "basic",
        "duration_days": 180,
        "amount_xtr": 2250,
        "is_promo": True,
        "first_payment_only": True,
        "full_price_xtr": 3150,
        "discount_percent": 29,
    },
    "stars_vip_3m_promo": {
        "title_ua": "VIP 3 місяці (-17%)",
        "title_ru": "VIP 3 месяца (-17%)",
        "title_en": "VIP 3 months (-17%)",
        "plan_type": "vip",
        "duration_days": 90,
        "amount_xtr": 3750,
        "is_promo": True,
        "first_payment_only": True,
        "full_price_xtr": 4500,
        "discount_percent": 17,
    },
    "stars_vip_6m_promo": {
        "title_ua": "VIP 6 місяців (-25%)",
        "title_ru": "VIP 6 месяцев (-25%)",
        "title_en": "VIP 6 months (-25%)",
        "plan_type": "vip",
        "duration_days": 180,
        "amount_xtr": 6750,
        "is_promo": True,
        "first_payment_only": True,
        "full_price_xtr": 9000,
        "discount_percent": 25,
    },
    "stars_vip_signals_10d": {
        "title_ua": "VIP Сигнали 10 днів",
        "title_ru": "VIP Сигналы 10 дней",
        "title_en": "VIP Signals 10 days",
        "plan_type": "vip_signals",
        "duration_days": 10,
        "amount_xtr": 399,
        "is_promo": False,
        "first_payment_only": False,
        "full_price_xtr": 399,
    },
}


def get_stars_plan(plan_key: str):
    return STARS_PLANS.get(plan_key)


def get_default_stars_plan_keys():
    return ["stars_basic_month", "stars_vip_1m"]


def get_promo_stars_plan_keys():
    """Promo plans for new users."""
    return ["stars_basic_6m_promo", "stars_vip_3m_promo", "stars_vip_6m_promo"]


def get_renewal_stars_plan_key(plan_type, duration_days=30):
    if plan_type == "vip":
        return "stars_vip_1m"
    return "stars_basic_month"
